-- or #
# SQL SELECT STATEMENT: 

SELECT * # This will return all information on the sakila actor table 
FROM sakila.actor; 


SELECT first_name, last_name 
FROM actor;


-- ASSIGNMENT:
# 1. OPEN YOUR MYSQL WORKBENCH, FROM THE SAKILA SCHEMA, USE SELECT STATEMENT AND QUERY THE FIRST 3 TABLES
-- 2. SELECT ANY COLUMNS - SINGULAR COLUMN
-- 3. SELECT ALL COLUMNS FROM THE COUNTRY TABLE IN  SAKILA DATABASE.

